# Generated by Django 4.2.5 on 2023-09-26 10:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='None', max_length=128, region='IN', unique=True),
        ),
    ]
