# Generated by Django 4.2.5 on 2023-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='farmlandmarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
