# Generated by Django 4.2.5 on 2023-09-26 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_user_farmlandmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
