# Generated by Django 4.2.5 on 2023-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20230926_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default='Y9OZCUZZYC76X', unique=True),
        ),
    ]
