# Generated by Django 4.2.5 on 2023-09-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=81217906396843285937806315912707957399, unique=True),
        ),
    ]
