# Generated by Django 4.2.5 on 2023-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=58315812757571063072983547604800165841, unique=True),
        ),
    ]
