# Generated by Django 4.2.5 on 2023-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=69221799959394712394654561610176468898, unique=True),
        ),
    ]
