# Generated by Django 4.2.5 on 2023-09-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=315180583404157104856448813794038862709, unique=True),
        ),
    ]
