# Generated by Django 4.2.5 on 2023-09-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=10855429615127288034710302957467978117, unique=True),
        ),
    ]
