# Generated by Django 4.2.5 on 2023-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=34101627020329800454466500293648428373, unique=True),
        ),
    ]
