# Generated by Django 4.2.5 on 2023-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=92772698551144729998081475380719810598, unique=True),
        ),
    ]
