# Generated by Django 4.2.5 on 2023-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=305226059195628027684358366753419934965, unique=True),
        ),
    ]
