# Generated by Django 4.2.5 on 2023-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=191121508458845280954505170004352731341, unique=True),
        ),
    ]
