# Generated by Django 4.2.5 on 2023-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=262560412727009234305928169757292155195, unique=True),
        ),
    ]
