# Generated by Django 4.2.5 on 2023-09-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=338559471620546777345608514471676561429, unique=True),
        ),
    ]
