# Generated by Django 4.2.5 on 2023-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=155476649717318772102686487718806680508, unique=True),
        ),
    ]
