# Generated by Django 4.2.5 on 2023-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=120735354110241490949316264902499414979, unique=True),
        ),
    ]
