# Generated by Django 4.2.5 on 2023-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=62563335819957577290376399439457143277, unique=True),
        ),
    ]
