# Generated by Django 4.2.5 on 2023-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=15736335438779215063450573755229940037, unique=True),
        ),
    ]
