# Generated by Django 4.2.5 on 2023-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerid', models.IntegerField()),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Available quantity', max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
