# Generated by Django 4.2.5 on 2023-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_produce_farmerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='farmerid',
            field=models.IntegerField(default=0),
        ),
    ]
